@WebApi_HostAddress = http://localhost:5202

GET {{WebApi_HostAddress}}/weatherforecast/?query=Git
Accept: application/json
# X-Database-Name: ContosoUniversity

###

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApi_HostAddress}}/weatherforecast/?query=Git;%20DROP%20TABLE%20Course
Accept: application/json

###

GET {{WebApi_HostAddress}}/weatherforecast/MyDepartCourses?query=Git
Accept: application/json

###

GET {{WebApi_HostAddress}}/weatherforecast/MyDepartCoursesSP?query=Git
Accept: application/json

###

GET {{WebApi_HostAddress}}/weatherforecast/MyDepartCoursesSQL?query=Git
Accept: application/json

###

GET {{WebApi_HostAddress}}/weatherforecast/CourseInstructors
Accept: application/json

###

GET {{WebApi_HostAddress}}/weatherforecast/DepartmentCoursesGroupJoin
Accept: application/json

###

POST {{WebApi_HostAddress}}/weatherforecast/AttachBehavior
Accept: application/json
Content-Type: application/json

{
    "CourseId": 24,
    "title": "Entity Framework Core 6 開發實戰",
    "credits": 5
}


###

GET {{WebApi_HostAddress}}/courses/
Accept: application/json

###

GET {{WebApi_HostAddress}}/courses?pageIndex=1&pageSize=5
Accept: application/json

###

GET {{WebApi_HostAddress}}/courses/1
Accept: application/json

###

PUT {{WebApi_HostAddress}}/courses/1
Accept: application/json
Content-Type: application/json

{
    "CourseId": 1,
    "title": "Entity Framework Core 6 開發實戰",
    "credits": 4
}

###

POST {{WebApi_HostAddress}}/courses
Accept: application/json
Content-Type: application/json

{
    "courseId": 1,
    "title": "Asp Net Core 8 Day 6",
    "credits": 4
}

###

DELETE  {{WebApi_HostAddress}}/courses/19
Accept: application/json